drop table app.tb_user;

create table app.tb_user(
    id integer primary key generated by default as identity,
    name varchar(20),
    username varchar(20),
    password varchar(32),
    token clob
);

insert into app.tb_user(name, username) values('Lorren Wang', 'lorren');
insert into app.tb_user(name, username) values('Sorimo Chen', 'sorimo');
insert into app.tb_user(name, username) values('Sara Du', 'sara');
insert into app.tb_user(name, username) values('Sarimo Rui', 'sarimo');
insert into app.tb_user(name, username) values('Mary Ka1', 'mary1');
insert into app.tb_user(name, username) values('Mary Ka2', 'mary2');
insert into app.tb_user(name, username) values('Mary Ka3', 'mary3');
insert into app.tb_user(name, username) values('Mary Ka4', 'mary4');
insert into app.tb_user(name, username) values('Mary Ka5', 'mary5');
insert into app.tb_user(name, username) values('Mary Ka6', 'mary6');