------------------------------------------------------------------------------------------------
-- JDBC Type            Database Type                   Additional comments
-- ARRAY                BLOB                            Will be read back as BLOB
-- BIGINT               BIGINT  
-- BINARY               CHAR(n) FOR BIT DATA    
-- BIT                  SMALLINT                        Cloudscape/Derby have no native boolean type
--                                                      Will be read back as SMALLINT
-- BLOB                 BLOB    
-- BOOLEAN              SMALLINT                        Cloudscape/Derby have no native boolean type
--                                                      Will be read back as BOOLEAN
-- CHAR                 CHAR    
-- CLOB                 CLOB    
-- DATALINK             LONG VARCHAR FOR BIT DATA       Will be read back as LONGVARBINARY
-- DATE                 DATE    
-- DECIMAL              DECIMAL 
-- DISTINCT             BLOB                            Will be read back as BLOB
-- DOUBLE               Cloudscape: DOUBLE PRECISION
--                      Derby: DOUBLE   
-- FLOAT                Cloudscape: DOUBLE PRECISION    Will be read back as DOUBLE
--                      Derby: DOUBLE 
-- INTEGER              INTEGER 
-- JAVA_OBJECT          BLOB                            Will be read back as BLOB
-- LONGVARBINARY        LONG VARCHAR FOR BIT DATA   
-- LONGVARCHAR          LONG VARCHAR    
-- NULL                 LONG VARCHAR FOR BIT DATA       Will be read back as LONGVARBINARY
-- NUMERIC              NUMERIC 
-- OTHER                BLOB                            Will be read back as BLOB
-- REAL                 REAL    
-- REF                  LONG VARCHAR FOR BIT DATA       Will be read back as LONGVARBINARY
-- SMALLINT             SMALLINT    
-- STRUCT               BLOB                            Will be read back as BLOB
-- TIME                 TIME    
-- TIMESTAMP            TIMESTAMP   
-- TINYINT              SMALLINT                        Will be read back as SMALLINT
-- VARBINARY            VARCHAR(n) FOR BIT DATA 
-- VARCHAR              VARCHAR 
------------------------------------------------------------------------------------------------
drop table app.oauth_client_details;
drop table app.oauth_client_token;
drop table app.oauth_access_token;
drop table app.oauth_refresh_token;
drop table app.oauth_code;
drop table app.authorities;
drop table app.users;
drop table app.tb_user;
drop table app.tb_account;

create table app.oauth_client_details (
  client_id VARCHAR(256) PRIMARY KEY,
  resource_ids VARCHAR(256),
  client_secret VARCHAR(256),
  scope VARCHAR(256),
  authorized_grant_types VARCHAR(256),
  web_server_redirect_uri VARCHAR(256),
  authorities VARCHAR(256),
  access_token_validity INTEGER,
  refresh_token_validity INTEGER,
  additional_information VARCHAR(4096),
  autoapprove VARCHAR(256)
);

create table app.oauth_client_token (
  token_id VARCHAR(256),
  token LONG VARCHAR FOR BIT DATA,
  authentication_id VARCHAR(256),
  user_name VARCHAR(256),
  client_id VARCHAR(256)
);

create table app.oauth_access_token (
  token_id VARCHAR(256),
  token LONG VARCHAR FOR BIT DATA,
  authentication_id VARCHAR(256),
  user_name VARCHAR(256),
  client_id VARCHAR(256),
  authentication LONG VARCHAR FOR BIT DATA,
  refresh_token VARCHAR(256)
);

create table app.oauth_refresh_token (
  token_id VARCHAR(256),
  token LONG VARCHAR FOR BIT DATA,
  authentication LONG VARCHAR FOR BIT DATA
);

create table app.oauth_code (
  code VARCHAR(256),
  authentication LONG VARCHAR FOR BIT DATA
);

create table app.users(
    username varchar(50) not null primary key,
    password varchar(50) not null,
    enabled boolean not null
);

create table app.authorities (
    username varchar(50) not null,
    authority varchar(50) not null,
    constraint fk_authorities_users foreign key(username) references users(username)
);
create unique index app.ix_auth_username on app.authorities (username, authority);

create table app.tb_user(
    id bigint primary key generated by default as identity,
    name varchar(20),
    email varchar(20),
    address varchar(255),
    phone varchar(20),
    enabled boolean,
    createtime timestamp,
    updatetime timestamp,
    creator bigint
);

create table app.tb_account(
    id bigint primary key generated by default as identity,
    userid bigint,
    username varchar(20),
    password varchar(32),
    token clob,
    enabled boolean,
    createtime timestamp,
    updatetime timestamp,
    creator bigint
);

insert into app.users(username, password, enabled) values('lorren', 'f64ea6bc04fe2f90ce611ced3772f034', true);
insert into app.authorities(username, authority) values('lorren', 'ROLE_USER');
insert into app.authorities(username, authority) values('lorren', 'ROLE_ADMIN');

insert into app.tb_user(id, name, email, address, phone, enabled, createtime, updatetime) values(-1, 'Lorren Wang', 'lorren@lorren.com', 'lorren address', '18600000000', true, current_timestamp, current_timestamp);
insert into app.tb_user(id, name, email, address, phone, enabled, createtime, updatetime) values(-2, 'Sorimo Chen', 'sorimo@lorren.com', 'sorimo address', '18600000000', true, current_timestamp, current_timestamp);
insert into app.tb_user(id, name, email, address, phone, enabled, createtime, updatetime) values(-3, 'Sara Du', 'sara@lorren.com', 'sara address', '18600000000', true, current_timestamp, current_timestamp);
insert into app.tb_user(id, name, email, address, phone, enabled, createtime, updatetime) values(-4, 'Sarimo Rui', 'sarimo@lorren.com', 'sarimo address', '18600000000', true, current_timestamp, current_timestamp);
insert into app.tb_user(id, name, email, address, phone, enabled, createtime, updatetime) values(-5, 'Mary Ka', 'mary@lorren.com', 'mary address', '18600000000', true, current_timestamp, current_timestamp);

insert into app.tb_account(id, userid, username, password, token, enabled, createtime, updatetime) values(-11, -1, 'lorren', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-21, -2, 'sorimo', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-31, -3, 'sara', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-41, -4, 'sarimo', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-51, -5, 'mary1', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-52, -5, 'mary2', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-53, -5, 'mary3', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-54, -5, 'mary4', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-55, -5, 'mary5', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);
insert into app.tb_account(id, userid,  username, password, token, enabled, createtime, updatetime) values(-56, -5, 'mary6', 'e99a18c428cb38d5f260853678922e03', 'e99a18c428cb38d5f260853678922e03', true, current_timestamp, current_timestamp);