create table app.tb_user(
    id integer primary key generated by default as identity,
    name varchar(20)
);

insert into app.tb_user(name) values('Lorren Wang');
insert into app.tb_user(name) values('Sorimo Chen');
insert into app.tb_user(name) values('Sara Du');
insert into app.tb_user(name) values('Sarimo Rui');
insert into app.tb_user(name) values('Mary Ka');